name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - conda-forge::termcolor
  - conda-forge::black
  - conda-forge::hydra-core
  - anaconda::ipython
  - anaconda::ipykernel
  - anaconda::path
  - pip
  - tqdm
  - cython
  - pip:
    - "black[jupyter]"
    - python-telegram-bot
    - pandas
    - numpy